# Generated by Django 6.0.1 on 2026-04-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('listing_type', models.CharField(choices=[('RENT', 'Rent'), ('SALE', 'Sale')], max_length=10)),
                ('property_type', models.CharField(choices=[('LAND', 'Land'), ('PLOT', 'Plot'), ('PG', 'PG/Hostel'), ('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('COMMERCIAL', 'Commercial')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(choices=[('SQFT', 'Sq. Ft.'), ('SQYD', 'Sq. Yards/Gaj'), ('SQMTR', 'Sq. Mtr.'), ('ACRE', 'Acres'), ('MARLA', 'Marla'), ('KANAL', 'Kanal')], default='SQYD', max_length=10)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pre-Listing',
                'verbose_name_plural': 'Pre-Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
