# Generated by Django 6.0.1 on 2026-01-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpsession',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otpsession',
            name='last_attempt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
