# Generated by Django 6.0.1 on 2026-01-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpsession_attempts_otpsession_last_attempt'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otpsession',
            index=models.Index(fields=['phone', 'created_at'], name='accounts_ot_phone_a2149f_idx'),
        ),
        migrations.AddIndex(
            model_name='otpsession',
            index=models.Index(fields=['session_id'], name='accounts_ot_session_116ea1_idx'),
        ),
    ]
