server {
    listen 80;
    # Replace with your EC2 Public IP, Elastic IP, or Domain Name
    server_name your_ec2_public_ip_here;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        alias /home/ubuntu/SEBackend/staticfiles/;
    }

    location /media/ {
        alias /home/ubuntu/SEBackend/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
